<?php
require_once __DIR__ . '/includes/legal.php';

$pageTitle = 'Privacy Policy';
$pageDescription = 'How BoatRent Cyprus collects, uses and protects your personal data — what we store when you send an inquiry or a reel, who we share it with, how long we keep it and the rights you have under the GDPR.';
$canonical = base_url() . '/privacy';

$b = business();
$identity = legal_identity_html();
$privacyEmail = e(legal_entity()['privacyEmail']);

$sections = [];

$sections[] = ['id' => 'who-we-are', 'title' => 'Who we are', 'html' => <<<HTML
<p>BoatRent Cyprus ("we", "us") runs the website at <strong>boatrentcyprus.com</strong>, where you can browse boats available for charter in Cyprus and send an inquiry about them. We are the <strong>data controller</strong> for the personal data described in this policy — meaning we decide why and how it is used.</p>
{$identity}
<p>For anything to do with your personal data — a question, a correction, or a request to delete it — write to <a href="mailto:{$privacyEmail}">{$privacyEmail}</a>.</p>
HTML];

$sections[] = ['id' => 'what-we-collect', 'title' => 'What we collect, and when', 'html' => <<<'HTML'
<p>We only collect data you actively give us, plus the minimum our web server needs to run. There is no account to create and nothing to sign up for.</p>

<h3>When you send a boat inquiry or use the contact form</h3>
<ul>
  <li>Your name</li>
  <li>Your email address</li>
  <li>Your phone number and dialling code, if you provide one</li>
  <li>The destination, dates and number of guests you are asking about</li>
  <li>The boat you were looking at, where the inquiry came from a boat page</li>
  <li>Anything you write in the message box</li>
</ul>

<h3>When you submit a guest reel</h3>
<ul>
  <li>Your name, and your email address if you give one</li>
  <li>The location, boat name and caption you enter</li>
  <li>The video file itself, and any still image captured from it</li>
  <li>Your IP address, recorded at the moment of upload</li>
</ul>
<div class="legal-note">
  <p>We record the IP address on reel uploads for one reason: to trace and block abuse of a form that accepts video files from the public. It is not used to profile you, is never linked to your browsing, and is deleted with the rest of the submission.</p>
</div>

<h3>Automatically, on every visit</h3>
<ul>
  <li>A <strong>session cookie</strong> set by our server, which keeps the contact form working across a page reload and keeps the owner login secure. See the <a href="/cookies">Cookie Policy</a>.</li>
  <li>Standard <strong>server access logs</strong> kept by our hosting provider — IP address, date and time, the page requested, and your browser's user-agent string. These are generated by the web server itself and are used for security and diagnosing faults.</li>
</ul>

<h3>What we do <em>not</em> collect</h3>
<p>To be specific, because a lot of sites say otherwise in the same breath:</p>
<ul>
  <li><strong>No analytics.</strong> No Google Analytics, no Meta pixel, no heatmaps, no session recording.</li>
  <li><strong>No advertising or tracking cookies</strong>, and no cross-site tracking of any kind.</li>
  <li><strong>No third-party fonts or embeds.</strong> Our fonts are served from our own server, so no request about you is made to Google or anyone else when a page loads.</li>
  <li><strong>No payment details.</strong> No card number ever reaches this website — we do not take payment here.</li>
  <li><strong>No special category data</strong> (health, beliefs, and so on). Please do not put any in a message box.</li>
</ul>
HTML];

$sections[] = ['id' => 'why-we-use-it', 'title' => 'Why we use it, and our legal basis', 'html' => <<<'HTML'
<p>Under the GDPR we have to name a lawful basis for each use. Ours are:</p>
<ul>
  <li><strong>To answer your inquiry and arrange a charter</strong> — Article 6(1)(b), steps taken at your request before entering a contract. Without your name and a way to reach you we cannot reply at all.</li>
  <li><strong>To pass your request to the charter operator</strong> who runs the boat you asked about — also Article 6(1)(b). This is the core of what we do; see <a href="#sharing">Who we share it with</a>.</li>
  <li><strong>To publish a guest reel you sent us</strong> — Article 6(1)(a), your consent, given by ticking the box on the upload form. You can withdraw it at any time and we will take the reel down.</li>
  <li><strong>To keep the site secure and working</strong> — Article 6(1)(f), our legitimate interest in preventing abuse, spam and fraud, and in fixing faults. We have weighed this against your interests and limited it to the minimum: logs and an upload IP.</li>
  <li><strong>To meet legal and accounting obligations</strong> where a charter goes ahead — Article 6(1)(c).</li>
</ul>
<p>We do not use your data for automated decision-making or profiling, and we do not send marketing emails. If we ever want to, we will ask you first and give you a way out in every message.</p>
HTML];

$sections[] = ['id' => 'sharing', 'title' => 'Who we share it with', 'html' => <<<'HTML'
<div class="legal-note">
  <p><strong>The important one:</strong> we are an intermediary. When you inquire about a boat, we pass the details you gave us to the <strong>licensed local operator</strong> who owns or runs that vessel, so they can confirm availability and price. That operator is a separate business and becomes an independent controller of your data, handling it under its own privacy policy. If you would like to know which operator a specific inquiry went to, ask us and we will tell you.</p>
</div>
<p>Beyond that, your data reaches only:</p>
<ul>
  <li><strong>Our hosting provider</strong>, which stores the website and its database on our behalf as a processor, under a contract that requires it to act only on our instructions.</li>
  <li><strong>Professional advisers or authorities</strong>, where the law requires it or we need to establish or defend a legal claim.</li>
</ul>
<p>We do not sell your personal data. We do not share it with advertisers, data brokers or marketing networks. There is no third party embedded in these pages collecting anything about you.</p>
HTML];

$sections[] = ['id' => 'transfers', 'title' => 'Where your data is stored', 'html' => <<<'HTML'
<p>Our website and database are hosted on servers within the European Economic Area, so your data stays under the GDPR by default.</p>
<p>Charter operators we work with are, in the ordinary course, based in Cyprus or elsewhere in the EEA. Where you ask us about a charter <strong>outside the EEA</strong> — the destinations covered on our <a href="/east-mediterranean">East Mediterranean page</a>, for instance — passing your inquiry on necessarily means sending your details to an operator in that country. Where that country has no European Commission adequacy decision, the transfer is made under Article 49(1)(b): it is necessary to perform the contract you asked us to arrange. We send only what the operator needs to quote for your trip.</p>
HTML];

$sections[] = ['id' => 'retention', 'title' => 'How long we keep it', 'html' => <<<'HTML'
<ul>
  <li><strong>Inquiries</strong> — kept for up to <strong>24 months</strong> from your last contact with us, so we can pick up a conversation you started and handle any dispute about a trip. Then deleted.</li>
  <li><strong>Inquiries that became a booking</strong> — kept as long as accounting and tax law requires, currently <strong>6 years</strong> in Cyprus.</li>
  <li><strong>Guest reels</strong> — kept while published, and deleted when you withdraw consent or ask us to remove them. Reels we decline are deleted shortly after review.</li>
  <li><strong>Server access logs</strong> — rotated and deleted on our hosting provider's normal schedule, a matter of weeks.</li>
</ul>
<p>You do not have to wait for any of these periods to run out. Ask us to delete your data and we will, unless we are legally required to keep it.</p>
HTML];

$sections[] = ['id' => 'your-rights', 'title' => 'Your rights', 'html' => <<<HTML
<p>The GDPR gives you the following rights over your personal data. They are free to use, and we will respond within <strong>one month</strong>.</p>
<ul>
  <li><strong>Access</strong> — a copy of the data we hold about you.</li>
  <li><strong>Rectification</strong> — correction of anything wrong or incomplete.</li>
  <li><strong>Erasure</strong> — deletion of your data where we no longer have a reason to keep it.</li>
  <li><strong>Restriction</strong> — a pause on our use of it while a dispute is sorted out.</li>
  <li><strong>Portability</strong> — your data in a machine-readable form, or sent to another provider.</li>
  <li><strong>Objection</strong> — to any use we base on legitimate interests.</li>
  <li><strong>Withdrawing consent</strong> — for anything we do on the basis of consent, such as a published reel. Withdrawing does not affect what was lawful beforehand.</li>
</ul>
<p>To use any of them, email <a href="mailto:{$privacyEmail}">{$privacyEmail}</a> from the address you contacted us with, or tell us enough to find your record. We may ask a question to confirm it is really you before we hand over or delete anything.</p>

<h3>Complaining to the regulator</h3>
<p>If you think we have handled your data badly, please tell us first — it is usually the fastest fix. You also have the right to complain directly to the Cypriot supervisory authority:</p>
<p><strong>Office of the Commissioner for Personal Data Protection</strong><br>
Iasonos 1, 1082 Nicosia, Cyprus<br>
<a href="https://www.dataprotection.gov.cy" target="_blank" rel="noopener noreferrer">www.dataprotection.gov.cy</a></p>
<p>If you live in another EU or EEA country, you may complain to your own national data protection authority instead.</p>
HTML];

$sections[] = ['id' => 'security', 'title' => 'How we protect it', 'html' => <<<'HTML'
<ul>
  <li>The whole site is served over an encrypted HTTPS connection.</li>
  <li>Inquiries are stored in a database that is not reachable from the web — the server is configured to refuse any direct request for it.</li>
  <li>Administrator passwords are stored only as a one-way hash, never in readable form, and the admin area sits behind a login.</li>
  <li>Forms are protected against cross-site request forgery, and uploaded videos are stored in a folder configured so that nothing in it can be executed as code.</li>
  <li>Access to inquiry data is limited to the people who need it to answer you.</li>
</ul>
<p>No website can promise perfect security. If a breach ever occurs that puts your rights at risk, we will notify the Commissioner within 72 hours and tell you directly where the law requires it.</p>
HTML];

$sections[] = ['id' => 'children', 'title' => 'Children', 'html' => <<<'HTML'
<p>This website is meant for adults arranging a charter. We do not knowingly collect data from children under 16. If you believe a child has sent us personal data — in a reel submission, for example — contact us and we will delete it promptly. Guests under 18 are of course welcome aboard; it is the person making the booking who needs to be an adult.</p>
HTML];

$sections[] = ['id' => 'changes', 'title' => 'Changes to this policy', 'html' => <<<'HTML'
<p>We update this policy when what we do with data changes — if we add analytics, a newsletter or online payment, for example. The "last updated" date at the top always reflects the current version. Where a change materially affects your rights we will make it obvious on the site rather than quietly editing this page.</p>
HTML];

include __DIR__ . '/includes/header.php';
render_legal_page([
    'eyebrow' => 'Your data, plainly explained',
    'title'   => 'Privacy Policy',
    'intro'   => 'What we collect when you inquire about a boat, why we need it, who else sees it, and how to get it back or deleted.',
], $sections);
include __DIR__ . '/includes/footer.php';
